(ns incremental.test.immediates
  (:use [incremental.compiler :only [compile-and-run]])
  (:use [clojure.test]))

(defmacro compiled= [program result]
  `(= (compile-and-run ~program) ~result))

(deftest integers
 (is (compiled= 42 "42"))
 (is (compiled= 0 "0"))
 (is (compiled= 1 "1"))
 (is (compiled= -1 "-1"))
 (is (compiled= 10 "10"))
 (is (compiled= -10 "-10"))
 (is (compiled= 2736 "2736"))
 (is (compiled= -2736 "-2736"))
 (is (compiled= 536870911 "536870911"))
 (is (compiled= -536870912 "-536870912")))

(deftest booleans
  (is (compiled= true "#t"))
  (is (compiled= false "#f")))

(deftest empty-list
  (is (compiled= '() "()")))

(deftest chars-short
  (is (compiled= \space " "))
  (is (compiled= \! "!"))
  (is (compiled= \a "a")))

(comment
  (deftest chars-all
    (is (compiled= \space " "))
    (is (compiled= \! "!"))
    (is (compiled= \" "\""))
    (is (compiled= \# "#"))
    (is (compiled= \$ "$"))
    (is (compiled= \% "%"))
    (is (compiled= \& "&"))
    (is (compiled= \' "'"))
    (is (compiled= \( "("))
    (is (compiled= \) ")"))
    (is (compiled= \* "*"))
    (is (compiled= \+ "+"))
    (is (compiled= \, ","))
    (is (compiled= \- "-"))
    (is (compiled= \. "."))
    (is (compiled= \/ "/"))
    (is (compiled= \0 "0"))
    (is (compiled= \1 "1"))
    (is (compiled= \2 "2"))
    (is (compiled= \3 "3"))
    (is (compiled= \4 "4"))
    (is (compiled= \5 "5"))
    (is (compiled= \6 "6"))
    (is (compiled= \7 "7"))
    (is (compiled= \8 "8"))
    (is (compiled= \9 "9"))
    (is (compiled= \: ":"))
    (is (compiled= \; ";"))
    (is (compiled= \< "<"))
    (is (compiled= \= "="))
    (is (compiled= \> ">"))
    (is (compiled= \? "?"))
    (is (compiled= \@ "@"))
    (is (compiled= \A "A"))
    (is (compiled= \B "B"))
    (is (compiled= \C "C"))
    (is (compiled= \D "D"))
    (is (compiled= \E "E"))
    (is (compiled= \F "F"))
    (is (compiled= \G "G"))
    (is (compiled= \H "H"))
    (is (compiled= \I "I"))
    (is (compiled= \J "J"))
    (is (compiled= \K "K"))
    (is (compiled= \L "L"))
    (is (compiled= \M "M"))
    (is (compiled= \N "N"))
    (is (compiled= \O "O"))
    (is (compiled= \P "P"))
    (is (compiled= \Q "Q"))
    (is (compiled= \R "R"))
    (is (compiled= \S "S"))
    (is (compiled= \T "T"))
    (is (compiled= \U "U"))
    (is (compiled= \V "V"))
    (is (compiled= \W "W"))
    (is (compiled= \X "X"))
    (is (compiled= \Y "Y"))
    (is (compiled= \Z "Z"))
    (is (compiled= \[ "["))
    (is (compiled= \\ "\\"))
    (is (compiled= \] "]"))
    (is (compiled= \^ "^"))
    (is (compiled= \_ "_"))
    (is (compiled= \` "`"))
    (is (compiled= \a "a"))
    (is (compiled= \b "b"))
    (is (compiled= \c "c"))
    (is (compiled= \d "d"))
    (is (compiled= \e "e"))
    (is (compiled= \f "f"))
    (is (compiled= \g "g"))
    (is (compiled= \h "h"))
    (is (compiled= \i "i"))
    (is (compiled= \j "j"))
    (is (compiled= \k "k"))
    (is (compiled= \l "l"))
    (is (compiled= \m "m"))
    (is (compiled= \n "n"))
    (is (compiled= \o "o"))
    (is (compiled= \p "p"))
    (is (compiled= \q "q"))
    (is (compiled= \r "r"))
    (is (compiled= \s "s"))
    (is (compiled= \t "t"))
    (is (compiled= \u "u"))
    (is (compiled= \v "v"))
    (is (compiled= \w "w"))
    (is (compiled= \x "x"))
    (is (compiled= \y "y"))
    (is (compiled= \z "z"))
    (is (compiled= \{ "{"))
    (is (compiled= \| "|"))
    (is (compiled= \} "}"))))
